"""Data models for ImpactScan domain objects."""
from __future__ import annotations

from typing import Literal

from pydantic import BaseModel, Field


def _default_spans() -> list[tuple[int, int]]:
    """Return an empty list of span tuples."""
    return []


class InstructionIntention(BaseModel):
    """Represents normalized intent extracted from a natural language instruction."""

    intention: str
    must_keywords: list[str] = Field(default_factory=list)
    should_keywords: list[str] = Field(default_factory=list)
    normalized_perspectives: list[str] = Field(default_factory=list)


class CandidateHit(BaseModel):
    """Single ripgrep match enriched with classification metadata."""

    file: str
    line_no: int
    byte_offset: int
    kind: Literal["code", "string", "comment", "preproc_disabled", "unknown"] = "unknown"
    text: str


def _default_hits() -> list[CandidateHit]:
    """Return an empty list of candidate hits."""
    return []


class CandidateFileWindow(BaseModel):
    """Aggregated view of ripgrep hits grouped by proximity within a file."""

    file: str
    spans: list[tuple[int, int]] = Field(default_factory=_default_spans)
    hits: list[CandidateHit] = Field(default_factory=_default_hits)
    num_occurrences: int = 0
    file_hash: str | None = None
    commit: str | None = None


class TriageResult(BaseModel):
    """Outcome of the lightweight triage LLM pass."""

    file: str
    window_index: int
    triage_decision: Literal["drop", "keep", "maybe"]
    relevance_score: float
    quick_reason: str
    hints: list[str] = Field(default_factory=list)


class ImpactAssessment(BaseModel):
    """Detailed assessment generated by the heavy-weight LLM stage."""

    file: str
    impact_level: Literal["none", "low", "medium", "high", "critical"]
    reason: str
    perspective_scores: dict[str, float] = Field(default_factory=dict)
    affected_apis: list[str] = Field(default_factory=list)
    risk_tags: list[str] = Field(default_factory=list)
    change_suggestion: str | None = None
    dependencies: list[str] = Field(default_factory=list)
    confidence: float
    lines: list[str] = Field(default_factory=list)
    num_occurrences: int = 0
    triage_decision: str | None = None
    commit: str | None = None
    hash: str | None = None


class ImpactRunSummary(BaseModel):
    """Aggregate metrics covering an ImpactScan execution."""

    files_scanned: int
    matches_total: int
    candidates_after_filter: int
    triage_kept: int
    analyzed: int
    output_paths: dict[str, str] = Field(default_factory=dict)
    token_usage: dict[str, int] = Field(default_factory=dict)
    elapsed_sec: float


__all__ = [
    "CandidateFileWindow",
    "CandidateHit",
    "ImpactAssessment",
    "ImpactRunSummary",
    "InstructionIntention",
    "TriageResult",
]
